{% set name = "sanic-routing" %}
{% set version = "0.7.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sanic-routing-{{ version }}.tar.gz
  sha256: 139ce88b3f054e7aa336e2ecc8459837092b103b275d3a97609a34092c55374d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - sanic_routing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sanic-org/sanic-routing/
  summary: Core routing component for Sanic
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicoddemus
